# Site settings
author: Lucy I Weltner
title: Adventures in Programming
header-img: img/home-bg.png
email: lucyiweltner@gmail.com
copyright_name: Lucy I Weltner
description: > # this means to ignore newlines until "baseurl:"
  I write about my programming challenges and successes
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  LucyWeltner

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
